/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#1f1f1f',
        'secondary-fixed-dim': '#c8c6c5',
        error: '#ffb4ab',
        tertiary: '#00dbe9',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'on-surface': '#e2e2e2',
        'inverse-primary': '#bb0058',
        'outline-variant': '#5c3f45',
        'surface-container-highest': '#353535',
        'on-secondary': '#313030',
        'primary-fixed': '#ffd9e0',
        'on-secondary-container': '#bab8b7',
        'on-tertiary-fixed-variant': '#004f54',
        'on-secondary-fixed': '#1c1b1b',
        primary: '#ffb1c3',
        'inverse-on-surface': '#303030',
        'inverse-surface': '#e2e2e2',
        'on-surface-variant': '#e5bcc4',
        'on-background': '#e2e2e2',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#00dbe9',
        'tertiary-fixed': '#7df4ff',
        'surface-tint': '#ffb1c3',
        'surface-variant': '#353535',
        'on-primary-container': '#590026',
        'error-container': '#93000a',
        surface: '#131313',
        'primary-fixed-dim': '#ffb1c3',
        'on-tertiary-container': '#002f33',
        'secondary-container': '#4a4949',
        outline: '#ac878f',
        'on-tertiary-fixed': '#002022',
        'surface-container-low': '#1b1b1b',
        secondary: '#c8c6c5',
        'surface-bright': '#393939',
        background: '#131313',
        'tertiary-container': '#00a0aa',
        'on-error': '#690005',
        'primary-container': '#ff4b89',
        'on-tertiary': '#00363a',
        'on-primary-fixed': '#3f0019',
        'on-primary': '#66002c',
        'secondary-fixed': '#e5e2e1',
        'on-secondary-fixed-variant': '#474646',
        'on-primary-fixed-variant': '#8f0041',
        'surface-dim': '#131313',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      boxShadow: {
        neon: '0 0 24px rgba(255, 177, 195, 0.22)',
        glass: '0 18px 70px rgba(0, 0, 0, 0.38)',
      },
    },
  },
  plugins: [],
}
